################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
3rdparty/libprocess/3rdparty/stout/tests \
3rdparty/libprocess/3rdparty/stout/tests/os \
3rdparty/libprocess/examples \
3rdparty/libprocess/src \
3rdparty/libprocess/src/metrics \
3rdparty/libprocess/src/ssl \
3rdparty/libprocess/src/tests \
build/3rdparty/distribute-0.6.26 \
build/3rdparty/distribute-0.6.26/tests/shlib_test \
build/3rdparty/leveldb/db \
build/3rdparty/leveldb/doc/bench \
build/3rdparty/leveldb/helpers/memenv \
build/3rdparty/leveldb/port \
build/3rdparty/leveldb/table \
build/3rdparty/leveldb/util \
build/3rdparty/libprocess/3rdparty/glog-0.3.3 \
build/3rdparty/libprocess/3rdparty/glog-0.3.3/src \
build/3rdparty/libprocess/3rdparty/glog-0.3.3/src/windows \
build/3rdparty/libprocess/3rdparty/gmock-1.7.0/fused-src \
build/3rdparty/libprocess/3rdparty/gmock-1.7.0/gtest/codegear \
build/3rdparty/libprocess/3rdparty/gmock-1.7.0/gtest/fused-src/gtest \
build/3rdparty/libprocess/3rdparty/gmock-1.7.0/gtest/samples \
build/3rdparty/libprocess/3rdparty/gmock-1.7.0/gtest/src \
build/3rdparty/libprocess/3rdparty/gmock-1.7.0/gtest/test \
build/3rdparty/libprocess/3rdparty/gmock-1.7.0/gtest/xcode/Samples/FrameworkSample \
build/3rdparty/libprocess/3rdparty/gmock-1.7.0/src \
build/3rdparty/libprocess/3rdparty/gmock-1.7.0/test \
build/3rdparty/libprocess/3rdparty \
build/3rdparty/libprocess/3rdparty/libev-4.15 \
build/3rdparty/libprocess/3rdparty/picojson-1.3.0/examples \
build/3rdparty/libprocess/3rdparty/picojson-1.3.0/picotest \
build/3rdparty/libprocess/3rdparty/picojson-1.3.0 \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/examples \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/gtest/codegear \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/gtest/fused-src/gtest \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/gtest/samples \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/gtest/src \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/gtest/test \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/gtest/xcode/Samples/FrameworkSample \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/python/google/protobuf/pyext \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/src \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/src/google/protobuf/compiler \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/src/google/protobuf/compiler/cpp \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/src/google/protobuf/compiler/java \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/src/google/protobuf/compiler/python \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/src/google/protobuf \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/src/google/protobuf/io \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/src/google/protobuf/stubs \
build/3rdparty/libprocess/3rdparty/protobuf-2.5.0/src/google/protobuf/testing \
build/3rdparty/libprocess/3rdparty/ry-http-parser-1c3624a \
build/3rdparty/libprocess \
build/3rdparty/zookeeper-3.4.5/contrib/zkfuse/src \
build/3rdparty/zookeeper-3.4.5/contrib/zkperl/build \
build/3rdparty/zookeeper-3.4.5/contrib/zkpython/src/c \
build/3rdparty/zookeeper-3.4.5/contrib/zktreeutil/src \
build/3rdparty/zookeeper-3.4.5/recipes/lock/src/c/src \
build/3rdparty/zookeeper-3.4.5/recipes/lock/src/c/tests \
build/3rdparty/zookeeper-3.4.5/recipes/queue/src/c/src \
build/3rdparty/zookeeper-3.4.5/recipes/queue/src/c/tests \
build/3rdparty/zookeeper-3.4.5/src/c \
build/3rdparty/zookeeper-3.4.5/src/c/generated \
build/3rdparty/zookeeper-3.4.5/src/c/src \
build/3rdparty/zookeeper-3.4.5/src/c/src/hashtable \
build/3rdparty/zookeeper-3.4.5/src/c/tests \
build/3rdparty/zookeeper-3.4.5/src/contrib/zkfuse/src \
build/3rdparty/zookeeper-3.4.5/src/contrib/zkperl/build \
build/3rdparty/zookeeper-3.4.5/src/contrib/zkpython/src/c \
build/3rdparty/zookeeper-3.4.5/src/contrib/zktreeutil/src \
build/3rdparty/zookeeper-3.4.5/src/recipes/lock/src/c/src \
build/3rdparty/zookeeper-3.4.5/src/recipes/lock/src/c/tests \
build/3rdparty/zookeeper-3.4.5/src/recipes/queue/src/c/src \
build/3rdparty/zookeeper-3.4.5/src/recipes/queue/src/c/tests \
build/include/mesos/appc \
build/include/mesos/authentication \
build/include/mesos/authorizer \
build/include/mesos/containerizer \
build/include/mesos/docker \
build/include/mesos/executor \
build/include/mesos/fetcher \
build/include/mesos/maintenance \
build/include/mesos/master \
build/include/mesos \
build/include/mesos/module \
build/include/mesos/quota \
build/include/mesos/scheduler \
build/include/mesos/slave \
build/include/mesos/uri \
build/include/mesos/v1/executor \
build/include/mesos/v1 \
build/include/mesos/v1/scheduler \
build/src/appc/.libs \
build/src/authentication/cram_md5/.libs \
build/src/authentication/http/.libs \
build/src/authorizer/.libs \
build/src/authorizer/local/.libs \
build/src/common/.libs \
build/src/docker/.libs \
build/src/exec/.libs \
build/src/executor/.libs \
build/src/files/.libs \
build/src/hdfs/.libs \
build/src/hook/.libs \
build/src/internal/.libs \
build/src/local/.libs \
build/src/logging/.libs \
build/src/master/.libs \
build/src/master/allocator/.libs \
build/src/master/allocator/mesos/.libs \
build/src/master/allocator/sorter/drf/.libs \
build/src/master \
build/src/messages/.libs \
build/src/messages \
build/src/module/.libs \
build/src/sched/.libs \
build/src/scheduler/.libs \
build/src/slave/.libs \
build/src/slave/container_loggers/.libs \
build/src/slave/containerizer/.libs \
build/src/slave/containerizer/mesos/.libs \
build/src/slave/containerizer/mesos/isolators/filesystem/.libs \
build/src/slave/containerizer/mesos/isolators/posix/.libs \
build/src/slave/containerizer/mesos/provisioner/.libs \
build/src/slave/containerizer/mesos/provisioner/appc/.libs \
build/src/slave/containerizer/mesos/provisioner/docker \
build/src/slave/qos_controllers/.libs \
src/appc \
src/authentication/cram_md5 \
src/authentication/http \
src/authorizer \
src/authorizer/local \
src/cli \
src/common \
src/docker \
src/examples \
src/exec \
src/executor \
src/files \
src/hdfs \
src/health-check \
src/hook \
src/internal \
src/java/jni \
src/jvm \
src/jvm/org/apache \
src/launcher \
src/linux \
src/linux/routing/diagnosis \
src/linux/routing/filter \
src/linux/routing \
src/linux/routing/link \
src/linux/routing/queueing \
src/local \
src/log \
src/log/tool \
src/logging \
src/master/allocator \
src/master/allocator/mesos \
src/master/allocator/sorter/drf \
src/master \
src/messages \
src/module \
src/python/native/src/mesos/native \
src/sched \
src/scheduler \
src/slave \
src/slave/container_loggers \
src/slave/containerizer \
src/slave/containerizer/mesos \
src/slave/containerizer/mesos/isolators/cgroups \
src/slave/containerizer/mesos/isolators/docker \
src/slave/containerizer/mesos/isolators/filesystem \
src/slave/containerizer/mesos/isolators/namespaces \
src/slave/containerizer/mesos/isolators/network \
src/slave/containerizer/mesos/isolators/posix \
src/slave/containerizer/mesos/provisioner/appc \
src/slave/containerizer/mesos/provisioner \
src/slave/containerizer/mesos/provisioner/backends \
src/slave/containerizer/mesos/provisioner/docker \
src/slave/qos_controllers \
src/slave/resource_estimators \
src/state \
src/tests \
src/tests/common \
src/tests/containerizer \
src/uri \
src/uri/fetchers \
src/usage \
src/v1 \
src/version \
src/watcher \
src/zookeeper \

