################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/tests/active_user_test_helper.cpp \
../src/tests/anonymous_tests.cpp \
../src/tests/attributes_tests.cpp \
../src/tests/authentication_tests.cpp \
../src/tests/authorization_tests.cpp \
../src/tests/cluster.cpp \
../src/tests/container_logger_tests.cpp \
../src/tests/containerizer.cpp \
../src/tests/cram_md5_authentication_tests.cpp \
../src/tests/credentials_tests.cpp \
../src/tests/disk_quota_tests.cpp \
../src/tests/environment.cpp \
../src/tests/examples_tests.cpp \
../src/tests/exception_tests.cpp \
../src/tests/executor_http_api_tests.cpp \
../src/tests/fault_tolerance_tests.cpp \
../src/tests/fetcher_cache_tests.cpp \
../src/tests/fetcher_tests.cpp \
../src/tests/files_tests.cpp \
../src/tests/flags.cpp \
../src/tests/gc_tests.cpp \
../src/tests/group_tests.cpp \
../src/tests/hdfs_tests.cpp \
../src/tests/health_check_tests.cpp \
../src/tests/hierarchical_allocator_tests.cpp \
../src/tests/hook_tests.cpp \
../src/tests/http_authentication_tests.cpp \
../src/tests/log_tests.cpp \
../src/tests/logging_tests.cpp \
../src/tests/main.cpp \
../src/tests/master_allocator_tests.cpp \
../src/tests/master_authorization_tests.cpp \
../src/tests/master_contender_detector_tests.cpp \
../src/tests/master_maintenance_tests.cpp \
../src/tests/master_quota_tests.cpp \
../src/tests/master_slave_reconciliation_tests.cpp \
../src/tests/master_tests.cpp \
../src/tests/master_validation_tests.cpp \
../src/tests/mesos.cpp \
../src/tests/metrics_tests.cpp \
../src/tests/module.cpp \
../src/tests/module_tests.cpp \
../src/tests/monitor_tests.cpp \
../src/tests/oversubscription_tests.cpp \
../src/tests/partition_tests.cpp \
../src/tests/paths_tests.cpp \
../src/tests/persistent_volume_endpoints_tests.cpp \
../src/tests/persistent_volume_tests.cpp \
../src/tests/protobuf_io_tests.cpp \
../src/tests/rate_limiting_tests.cpp \
../src/tests/reconciliation_tests.cpp \
../src/tests/registrar_tests.cpp \
../src/tests/registrar_zookeeper_tests.cpp \
../src/tests/repair_tests.cpp \
../src/tests/reservation_endpoints_tests.cpp \
../src/tests/reservation_tests.cpp \
../src/tests/resource_offers_tests.cpp \
../src/tests/resources_tests.cpp \
../src/tests/role_tests.cpp \
../src/tests/scheduler_driver_tests.cpp \
../src/tests/scheduler_event_call_tests.cpp \
../src/tests/scheduler_http_api_tests.cpp \
../src/tests/scheduler_tests.cpp \
../src/tests/script.cpp \
../src/tests/slave_recovery_tests.cpp \
../src/tests/slave_tests.cpp \
../src/tests/sorter_tests.cpp \
../src/tests/state_tests.cpp \
../src/tests/status_update_manager_tests.cpp \
../src/tests/teardown_tests.cpp \
../src/tests/uri_fetcher_tests.cpp \
../src/tests/uri_tests.cpp \
../src/tests/utils.cpp \
../src/tests/values_tests.cpp \
../src/tests/zookeeper.cpp \
../src/tests/zookeeper_test_server.cpp \
../src/tests/zookeeper_tests.cpp \
../src/tests/zookeeper_url_tests.cpp 

OBJS += \
./src/tests/active_user_test_helper.o \
./src/tests/anonymous_tests.o \
./src/tests/attributes_tests.o \
./src/tests/authentication_tests.o \
./src/tests/authorization_tests.o \
./src/tests/cluster.o \
./src/tests/container_logger_tests.o \
./src/tests/containerizer.o \
./src/tests/cram_md5_authentication_tests.o \
./src/tests/credentials_tests.o \
./src/tests/disk_quota_tests.o \
./src/tests/environment.o \
./src/tests/examples_tests.o \
./src/tests/exception_tests.o \
./src/tests/executor_http_api_tests.o \
./src/tests/fault_tolerance_tests.o \
./src/tests/fetcher_cache_tests.o \
./src/tests/fetcher_tests.o \
./src/tests/files_tests.o \
./src/tests/flags.o \
./src/tests/gc_tests.o \
./src/tests/group_tests.o \
./src/tests/hdfs_tests.o \
./src/tests/health_check_tests.o \
./src/tests/hierarchical_allocator_tests.o \
./src/tests/hook_tests.o \
./src/tests/http_authentication_tests.o \
./src/tests/log_tests.o \
./src/tests/logging_tests.o \
./src/tests/main.o \
./src/tests/master_allocator_tests.o \
./src/tests/master_authorization_tests.o \
./src/tests/master_contender_detector_tests.o \
./src/tests/master_maintenance_tests.o \
./src/tests/master_quota_tests.o \
./src/tests/master_slave_reconciliation_tests.o \
./src/tests/master_tests.o \
./src/tests/master_validation_tests.o \
./src/tests/mesos.o \
./src/tests/metrics_tests.o \
./src/tests/module.o \
./src/tests/module_tests.o \
./src/tests/monitor_tests.o \
./src/tests/oversubscription_tests.o \
./src/tests/partition_tests.o \
./src/tests/paths_tests.o \
./src/tests/persistent_volume_endpoints_tests.o \
./src/tests/persistent_volume_tests.o \
./src/tests/protobuf_io_tests.o \
./src/tests/rate_limiting_tests.o \
./src/tests/reconciliation_tests.o \
./src/tests/registrar_tests.o \
./src/tests/registrar_zookeeper_tests.o \
./src/tests/repair_tests.o \
./src/tests/reservation_endpoints_tests.o \
./src/tests/reservation_tests.o \
./src/tests/resource_offers_tests.o \
./src/tests/resources_tests.o \
./src/tests/role_tests.o \
./src/tests/scheduler_driver_tests.o \
./src/tests/scheduler_event_call_tests.o \
./src/tests/scheduler_http_api_tests.o \
./src/tests/scheduler_tests.o \
./src/tests/script.o \
./src/tests/slave_recovery_tests.o \
./src/tests/slave_tests.o \
./src/tests/sorter_tests.o \
./src/tests/state_tests.o \
./src/tests/status_update_manager_tests.o \
./src/tests/teardown_tests.o \
./src/tests/uri_fetcher_tests.o \
./src/tests/uri_tests.o \
./src/tests/utils.o \
./src/tests/values_tests.o \
./src/tests/zookeeper.o \
./src/tests/zookeeper_test_server.o \
./src/tests/zookeeper_tests.o \
./src/tests/zookeeper_url_tests.o 

CPP_DEPS += \
./src/tests/active_user_test_helper.d \
./src/tests/anonymous_tests.d \
./src/tests/attributes_tests.d \
./src/tests/authentication_tests.d \
./src/tests/authorization_tests.d \
./src/tests/cluster.d \
./src/tests/container_logger_tests.d \
./src/tests/containerizer.d \
./src/tests/cram_md5_authentication_tests.d \
./src/tests/credentials_tests.d \
./src/tests/disk_quota_tests.d \
./src/tests/environment.d \
./src/tests/examples_tests.d \
./src/tests/exception_tests.d \
./src/tests/executor_http_api_tests.d \
./src/tests/fault_tolerance_tests.d \
./src/tests/fetcher_cache_tests.d \
./src/tests/fetcher_tests.d \
./src/tests/files_tests.d \
./src/tests/flags.d \
./src/tests/gc_tests.d \
./src/tests/group_tests.d \
./src/tests/hdfs_tests.d \
./src/tests/health_check_tests.d \
./src/tests/hierarchical_allocator_tests.d \
./src/tests/hook_tests.d \
./src/tests/http_authentication_tests.d \
./src/tests/log_tests.d \
./src/tests/logging_tests.d \
./src/tests/main.d \
./src/tests/master_allocator_tests.d \
./src/tests/master_authorization_tests.d \
./src/tests/master_contender_detector_tests.d \
./src/tests/master_maintenance_tests.d \
./src/tests/master_quota_tests.d \
./src/tests/master_slave_reconciliation_tests.d \
./src/tests/master_tests.d \
./src/tests/master_validation_tests.d \
./src/tests/mesos.d \
./src/tests/metrics_tests.d \
./src/tests/module.d \
./src/tests/module_tests.d \
./src/tests/monitor_tests.d \
./src/tests/oversubscription_tests.d \
./src/tests/partition_tests.d \
./src/tests/paths_tests.d \
./src/tests/persistent_volume_endpoints_tests.d \
./src/tests/persistent_volume_tests.d \
./src/tests/protobuf_io_tests.d \
./src/tests/rate_limiting_tests.d \
./src/tests/reconciliation_tests.d \
./src/tests/registrar_tests.d \
./src/tests/registrar_zookeeper_tests.d \
./src/tests/repair_tests.d \
./src/tests/reservation_endpoints_tests.d \
./src/tests/reservation_tests.d \
./src/tests/resource_offers_tests.d \
./src/tests/resources_tests.d \
./src/tests/role_tests.d \
./src/tests/scheduler_driver_tests.d \
./src/tests/scheduler_event_call_tests.d \
./src/tests/scheduler_http_api_tests.d \
./src/tests/scheduler_tests.d \
./src/tests/script.d \
./src/tests/slave_recovery_tests.d \
./src/tests/slave_tests.d \
./src/tests/sorter_tests.d \
./src/tests/state_tests.d \
./src/tests/status_update_manager_tests.d \
./src/tests/teardown_tests.d \
./src/tests/uri_fetcher_tests.d \
./src/tests/uri_tests.d \
./src/tests/utils.d \
./src/tests/values_tests.d \
./src/tests/zookeeper.d \
./src/tests/zookeeper_test_server.d \
./src/tests/zookeeper_tests.d \
./src/tests/zookeeper_url_tests.d 


# Each subdirectory must supply rules for building sources it contributes
src/tests/%.o: ../src/tests/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -I"/Users/gokrokve/work/intel/mesos-openstack/mesos/build/include" -I"/Users/gokrokve/work/intel/mesos-openstack/mesos/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


